services:
  buildorders:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - infrastructure_infra-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.buildorders.rule=Host(`buildorders.aperture-agency.org`)"
      - "traefik.http.routers.buildorders.entrypoints=websecure"
      - "traefik.http.routers.buildorders.tls=true"
      - "traefik.http.routers.buildorders.tls.certresolver=cf"
      - "traefik.http.services.buildorders.loadbalancer.server.port=80"

networks:
  infrastructure_infra-network:
    external: true
